package apshomebe.caregility.com.websocket.model;

public enum EApsTransferTransactionName {
	INITIATED_APS_TRNSACTION, PREPARE_DATA, CHECKING_DEVICE_READY, DEVICE_READY_CONFIRMED, CONFIG_UPDATE_STARTED,
	CONFIG_UPDATE_FAILED, CONFIG_UPDATE_SUCCESS, TRANSFERRING_TRANSFOR_INFO, TRANSFER_SUCCESS, TRANSFER_FAILED,
	TIME_OUT;
}
